name: 'Docker Version - 1'
    
on:
  workflow_dispatch:  # Allow manual triggers
    inputs:
      delays:
        description: 'Delayed time (Optional) 可选延迟时间'
        required: false
# schedule:
#   - cron: '0 2 21 * *' # change here for `cron`; Schedule on CST 10 during 20th day of every month.

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Send Message to Wechat'
          uses: HollowMan6/Wechat-Timed-Message@main
          with:
            DELAYS: ${{ github.event.inputs.delays }}
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            OPENID: ${{ secrets.OPENID }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
            TITLE: ${{ secrets.TITLE }}
            MSG: ${{ secrets.MSG }}
        - name: 'Re-run workflow if failed and GPATOKEN set'
          if: ${{ failure() }}
          run: |
            workflow_url=`curl $GITHUB_API_URL/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | grep workflow_url | cut -d \" -f 4` \
            && curl \
            -X POST \
            -H 'authorization: token ${{ secrets.GPATOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            $workflow_url/dispatches \
            -d '{"ref":"${{ github.ref }}", "inputs": { "delays": "30m" }}'
